<a href="https://colab.research.google.com/github/PhamNhatHuy711/Huy/blob/main/Bai_tap_4%2C5_13_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1


In [35]:
from random import random, randint, uniform

In [ ]:
a = []
for i in range(7):
  x = int(int(input()))
  a.append(x)
print(a)

1
2
3
4
5
6
7
[1, 2, 3, 4, 5, 6, 7]


Bài 2


In [37]:

b = []
for i in range(30):
  x = randint(-10, 10)
  b.append(x)
print(b)

[-10, 6, 9, -9, 3, -2, -4, 5, -5, -1, -1, 6, 9, 4, 5, -8, -3, -8, -3, 0, 9, -3, -1, 1, -2, 10, 10, 0, -7, 1]


Bài 3

In [ ]:
#cách 1
c = []
z = []
min = -5.7
max = 6.9
for i in range(30):
  f = min + (max-min)*random()
  c.append(f)
print(c)
#cách 2
for i in range(30):
  f = uniform(-5.7, 6.9)
  z.append(f)
print(z)

[-2.4392234715353127, 6.020124078923907, -3.0091377246408255, 6.65132334159147, 3.0631879280154584, 3.7196094615346516, -3.600209931336922, -3.12216904589362, 5.379173058771639, -4.407897753914487, 6.812862326974929, -1.8401852823092644, 3.411690202104359, 0.25727828332050073, 1.3519363509844418, 2.6529462561969313, -0.8967688919947499, 4.5932084487846145, -4.388914434627435, 0.6255931520778457, 6.392080917985468, 1.2038363450072893, 4.234467721580651, 4.093069576648053, 0.18254499706947236, 5.346680368722422, -0.166237220980328, -2.9764917671019053, 3.5539157253284293, 3.3383408326539277]
[6.716525066596373, -4.678488033232496, -3.7240955075170543, -2.221472558903107, 3.681890956693258, -4.010511274824838, 2.274693799401187, -0.02143035072783661, 1.0418207281974459, -1.9453715235704627, -1.2338348840784166, 2.459249340172504, -1.184454392015529, -1.4521576393335076, 0.18243677225696064, -5.1511436302465015, 2.267047069028063, -4.903905471273296, -1.6903503082219, 1.6260414545202577, 4

Bài 4

In [ ]:
d=[]
for i in range(10):
  x = randint(-10, 10)
  d.append(x)
print(d)
a = float(input())
for i in range(10):
  d[i] = d[i]*a
print(d)

[8, 8, 7, -10, -7, 5, 4, -3, 9, -2]
4
[32.0, 32.0, 28.0, -40.0, -28.0, 20.0, 16.0, -12.0, 36.0, -8.0]


Bài 5

In [ ]:
x = []
y = []
for i in range(15):
  z = randint(-10, 10)
  x.append(z)
for i in range(15):
  z = randint(-10, 10)
  y.append(z)
print(x)
print(y)
for i in range(15):
  x[i] = x[i] + y[i]
print("Tổng 2 vecto", x)

[-1, -3, 2, -4, -10, -6, 5, 8, 8, -5, -4, 7, -8, 8, 4]
[-9, 7, -8, 10, -5, -10, -8, -5, -2, 9, 7, 6, -2, 5, -4]
Tổng 2 vecto [-10, 4, -6, 6, -15, -16, -3, 3, 6, 4, 3, 13, -10, 13, 0]


Bài 6

In [ ]:
x = []
y = []
for i in range(10):
  z = randint(-10, 10)
  x.append(z)
for i in range(10):
  z = randint(-10, 10)
  y.append(z)
print(x)
print(y)
for i in range(10):
  x[i] = x[i] * y[i]
print("tích 2 vecto", x)

[-9, 10, -10, 5, 8, -4, 2, -9, -5, 4]
[7, 0, -10, 4, 9, -9, -5, -4, 1, 4]
tích 2 vecto [-63, 0, 100, 20, 72, 36, -10, 36, -5, 16]


Bài 7

In [ ]:
x = []
y = []
for i in range(10):
  z = randint(-10, 10)
  x.append(z)
for i in range(10):
  z = randint(-10, 10)
  y.append(z)
print(x)
print(y)
for i in range(10):
  x[i] = x[i] * y[i]
tong = 0
for i in range(10):
  tong = tong + x[i]
print("tích vô hướng 2 vecto", tong)

[6, 8, 1, -7, 9, 10, 7, -9, 5, -2]
[1, -1, 1, -3, -5, -2, -5, -7, -9, -7]
tích vô hướng 2 vecto -48


Bài 8

In [39]:
from numpy import random
a = random.randint(0, 10, size = (3, 5))
print(a)
print("a[2,3] là: ", a[1][2])

[[0 1 9 6 6]
 [5 9 3 9 4]
 [7 8 0 1 0]]
a[2,3] là:  3


BÀi 9

In [45]:
b = random.randint(0, 10, size = (3, 5))
print(b)
a = float(input())
for i in range(3):
  for j in range(5):
    b[i][j] = b[i][j]*a
print(b)

[[1 5 6 5 4]
 [2 6 9 2 7]
 [1 5 1 9 7]]
2
[[ 2 10 12 10  8]
 [ 4 12 18  4 14]
 [ 2 10  2 18 14]]


Bài 10

In [34]:
a = random.randint(0, 10, size = (3, 5))
print(a)
b = random.randint(0, 10, size = (3, 5))
print(b)
c = a + b
print(c)

[[7 5 8 0 4]
 [2 8 0 6 3]
 [2 2 6 3 2]]
[[5 3 5 9 9]
 [7 1 7 2 6]
 [9 1 3 3 1]]
[[12  8 13  9 13]
 [ 9  9  7  8  9]
 [11  3  9  6  3]]


Bài 11



In [42]:
a = random.randint(0, 10, size = (3, 4))
print(a)
b = random.randint(0, 10, size = (4, 5))
print(b)
c = a.dot(b)
print(c)

[[6 4 3 3]
 [3 6 3 4]
 [3 4 3 8]]
[[4 2 0 4 9]
 [8 2 0 2 5]
 [8 9 0 7 5]
 [3 6 8 4 5]]
[[ 89  65  24  65 104]
 [ 96  69  32  61  92]
 [ 92  89  64  73 102]]
