<a href="https://colab.research.google.com/github/PhamNhatHuy711/Huy/blob/main/Baitaptailop2_30_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bai1

1

In [3]:
import numpy as np

In [9]:
n = abs(int(input()))
x = np.random.randint(low=0,high=10, size=n)
print(x)

10
[8 2 5 8 3 7 8 8 6 6]


2

In [12]:
print(np.sqrt(x))
print(np.cos(x))
print(np.sin(x))
print(np.log(x))

[2.82842712 1.41421356 2.23606798 2.82842712 1.73205081 2.64575131
 2.82842712 2.82842712 2.44948974 2.44948974]
[-0.14550003 -0.41614684  0.28366219 -0.14550003 -0.9899925   0.75390225
 -0.14550003 -0.14550003  0.96017029  0.96017029]
[ 0.98935825  0.90929743 -0.95892427  0.98935825  0.14112001  0.6569866
  0.98935825  0.98935825 -0.2794155  -0.2794155 ]
[2.07944154 0.69314718 1.60943791 2.07944154 1.09861229 1.94591015
 2.07944154 2.07944154 1.79175947 1.79175947]


3

In [20]:
a = np.sqrt(x)
b = np.cos(x)
c = np.sin(x)
d = np.log(x)
print(np.round(a,2))
print(np.round(b,2))
print(np.round(c,2))
print(np.round(d,2))

[2.83 1.41 2.24 2.83 1.73 2.65 2.83 2.83 2.45 2.45]
[-0.15 -0.42  0.28 -0.15 -0.99  0.75 -0.15 -0.15  0.96  0.96]
[ 0.99  0.91 -0.96  0.99  0.14  0.66  0.99  0.99 -0.28 -0.28]
[2.08 0.69 1.61 2.08 1.1  1.95 2.08 2.08 1.79 1.79]


4

In [24]:
n = abs(int(input()))
m = abs(int(input()))
y = np.random.randint(0,10,(m,n))
a = np.sqrt(y)
b = np.cos(y)
c = np.sin(y)
d = np.log(y)
e = np.tan(y)
print(np.round(a,3))
print(np.round(b,3))
print(np.round(c,3))
print(np.round(d,3))
print(np.round(e,3))


3
5
[[2.    2.828 2.   ]
 [2.646 1.732 2.828]
 [2.236 1.    1.   ]
 [1.414 2.    1.   ]
 [2.646 1.414 2.828]]
[[-0.654 -0.146 -0.654]
 [ 0.754 -0.99  -0.146]
 [ 0.284  0.54   0.54 ]
 [-0.416 -0.654  0.54 ]
 [ 0.754 -0.416 -0.146]]
[[-0.757  0.989 -0.757]
 [ 0.657  0.141  0.989]
 [-0.959  0.841  0.841]
 [ 0.909 -0.757  0.841]
 [ 0.657  0.909  0.989]]
[[1.386 2.079 1.386]
 [1.946 1.099 2.079]
 [1.609 0.    0.   ]
 [0.693 1.386 0.   ]
 [1.946 0.693 2.079]]
[[ 1.158 -6.8    1.158]
 [ 0.871 -0.143 -6.8  ]
 [-3.381  1.557  1.557]
 [-2.185  1.158  1.557]
 [ 0.871 -2.185 -6.8  ]]


Bai2

In [28]:
x = np.linspace(start=-100, stop=
100, num=1000, dtype=float)
a = 3*x*x - 2*x - 4
b = np.cos(a)
c = np.sin(a)
print(np.round(b,2))
print(np.round(c,2))


[ 0.55 -0.42 -0.94 -0.98 -0.89 -0.86 -0.94 -1.   -0.75  0.06  0.93  0.52
 -0.88 -0.2   0.94 -0.9   0.53 -0.24  0.17 -0.33  0.68 -0.98  0.76  0.27
 -1.   -0.11  0.93  0.79  0.1  -0.45 -0.72 -0.78 -0.67 -0.34  0.29  0.92
  0.76 -0.47 -0.87  0.7   0.28 -0.9   0.99 -0.89  0.84 -0.91  1.   -0.85
  0.16  0.81 -0.76 -0.66  0.57  0.99  0.58  0.02 -0.34 -0.45 -0.33  0.02
  0.58  0.99  0.56 -0.67 -0.75  0.82  0.14 -0.84  1.   -0.92  0.85 -0.9
  1.   -0.88  0.25  0.73 -0.85 -0.51  0.73  0.93  0.33 -0.29 -0.63 -0.74
 -0.68 -0.4   0.16  0.83  0.9  -0.17 -0.99  0.33  0.71 -0.99  0.73 -0.4
  0.25 -0.32  0.6  -0.93  0.91 -0.11 -0.92  0.44  0.96  0.16 -0.68 -0.99
 -0.97 -0.91 -0.93 -1.   -0.89 -0.32  0.64  0.92 -0.32 -0.88  0.79  0.01
 -0.63  0.9  -0.97  0.96 -0.84  0.45  0.3  -0.97  0.55  0.78 -0.49 -0.99
 -0.5   0.17  0.58  0.74  0.72  0.51  0.02 -0.67 -0.99 -0.19  0.96  0.15
 -0.97  0.76 -0.15 -0.31  0.52 -0.5   0.27  0.22 -0.82  0.94  0.01 -0.99
 -0.02  0.93  0.84  0.27 -0.21 -0.44 -0.44 -0.22  0.2