<a href="https://colab.research.google.com/github/PhamNhatHuy711/Huy/blob/main/BTtailop1_30_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1


In [3]:
import numpy as np

In [2]:
v1 = np.arange(15, dtype=int)
v2 = np.arange(start=-5, stop =
10, dtype=int)
print(v1)
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9]


2

In [4]:
v3 = np.linspace(start=-2, stop=
3, num=15, dtype=float)
print(v3)

[-2.         -1.64285714 -1.28571429 -0.92857143 -0.57142857 -0.21428571
  0.14285714  0.5         0.85714286  1.21428571  1.57142857  1.92857143
  2.28571429  2.64285714  3.        ]


3

In [5]:
np.random.seed(123)
v4 = np.random.randint(2, size=10)
print(v4)
v5 = np.random.randint(low=-3,high=3, size=10)
print(v5)

[0 1 0 0 0 0 0 1 1 0]
[ 0 -2 -2 -3 -2 -2 -3 -3 -2  0]


4

In [6]:
v6 = np.random.random_sample(10)
print(v6)
a =-2
b = 3
v7 = (b -
a)*np.random.random_sample(10) + a
print(v7)

[0.24475928 0.69475518 0.5939024  0.63179202 0.44025718 0.08372648
 0.71233018 0.42786349 0.2977805  0.49208478]
[ 1.70148195 -0.21135541  0.08604974  1.27360654 -0.13099287 -0.82743562
  2.93997643  1.82997975  1.88502219 -1.86009022]


5

In [9]:
n = abs(int(input()))
v8 = np.linspace(start=-5, stop=
10, num=n, dtype=int)
v9 = np.linspace(start=-2, stop=
7, num=n, dtype=int)
v10 = np.random.randint(low=-3,high=12, size=n)
v11 = np.random.randint(low=0,high=7, size=n)
print(v8)
print(v9)
print(v10)
print(v11)


8
[-5 -3 -1  1  3  5  7 10]
[-2 -1  0  1  3  4  5  7]
[-3  3 11  1  4  8  3  4]
[1 3 2 5 1 2 4 0]


6

In [10]:
print(v7.shape)
print(v7.ndim)

(10,)
1


7

In [11]:
a = 5
v12 = 5*v5
print(v12)

[  0 -10 -10 -15 -10 -10 -15 -15 -10   0]


8

In [12]:
x = np.random.randint(5, size=10)
y = np.random.randint(low=-
5,high=5, size=10)
z = x + y
print('z = ', z)

z =  [-3  5  0 -1  1  7  6  5 -3 -2]


9

In [14]:
x = np.random.randint(5, size=10)
y = np.random.randint(low=-
5,high=5, size=10)
print('x = ', x)
print('y = ', y)
n = np.dot(x, y)
print('n = ', n)

x =  [1 0 3 1 3 4 4 1 4 4]
y =  [-2 -2  2  1  3  1 -1 -1  2 -5]
n =  1


10

In [15]:
x = np.random.randint(5, size=10)
y = np.random.randint(low=-
5,high=5, size=10)
print('x = ', x)
print('y = ', y)
h = np.multiply(x, y)
print('Hadamard product = ', h)

x =  [0 1 0 0 4 2 2 0 1 0]
y =  [ 2  4 -4  2 -4  2  4  3  2 -4]
Hadamard product =  [  0   4   0   0 -16   4   8   0   2   0]
